@baseUrl = http://localhost:4444

# GET health
# @name healthCheck
GET {{baseUrl}}/health

#### Get Vessels
# @name getVesselsByID
GET {{baseUrl}}/api/v1/vessel/26

###
# Get Vessels
# @name getVessels
GET {{baseUrl}}/api/v1/vessel

###
# Get Vessels
# @name getVesselsByID
GET {{baseUrl}}/api/v1/vessel/26

###
# Get Vessels
# @name getVesselsByImo
GET {{baseUrl}}/api/v1/vessel/imo/9142954

###
# Get Vessels
# @name getVesselsByMmsi
GET {{baseUrl}}/api/v1/vessel/mmsi/229543000

###
